spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_data_rest
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    rest:
      base-path: /api/
server:
  error:
    include-message: always
